const beginnings = [
"In the midst of chaos",
"As the sun dipped below the horizon",
"With a sense of anticipation",
"After years of searching",
"In a distant galaxy",
"Amidst the bustling city",
"With a spark of inspiration",
"As the first rays of sunlight touched the ground",
"Under the twinkling stars",
"Along the winding path",
"With a heart full of dreams",
"As the clock struck midnight",
"In the heart of the jungle",
"Amidst the tranquil silence",
"With bated breath",
"After a long and tiring journey",
"In a parallel universe",
"With the scent of freshly bloomed flowers",
"Across the vast desert",
"As the storm raged on",
"In the realm of imagination",
"With a glimmer of hope",
"Amidst the ancient ruins",
"With a sense of wonder",
"As the waves crashed against the shore",
"Under the canopy of stars",
"With the echo of laughter",
"Amidst the vibrant colors",
"With the dawn of a new day",
"In the heart of the wilderness",
"With a hint of mystery",
"As the door creaked open",
"Under the watchful gaze of the moon",
"With the taste of adventure",
"Amidst the fragrant aroma",
"With a sense of purpose",
"After a long winter’s night",
"In the land of dreams",
"With a touch of magic",
"As the old oak tree stood tall",
"Amidst the hustle and bustle",
"With the melody of birdsong",
"Under the blanket of snow",
"With a feeling of déjà vu",
"As the ancient prophecy foretold",
"In the world of make-believe",
"With a rush of adrenaline",
"Amidst the falling leaves",
"With the promise of tomorrow",
"As the final chapter began"]

const middles = [
"discovered a hidden treasure",
"embarked on a daring adventure to find",
"whispered secrets to the wind",
"encountered unexpected challenges while",
"crafted a masterpiece, showcasing",
"explored the depths of the ocean, discovering",
"witnessed a miracle, as",
"raced against time to save",
"built a time machine, hoping to visit",
"solved the enigma by deciphering",
"faced the ultimate test, proving",
"uncovered a conspiracy involving",
"befriended a mysterious stranger named",
"concocted a potion with the power to",
"stumbled upon a long-lost civilization",
"painted a vivid picture of",
"composed a symphony that echoed",
"mastered the art of",
"encountered a parallel universe where",
"invented a gadget that could",
"deciphered ancient hieroglyphics, revealing",
"forged an unbreakable bond with",
"navigated through treacherous waters, guided by",
"time-traveled to a future where",
"forged a sword imbued with",
"deciphered an ancient map leading to",
"created a cure for a deadly disease",
"unraveled the mystery behind",
"composed a love letter to",
"ventured into the unknown, guided by",
"uncovered a conspiracy that threatened",
"wrote a bestseller chronicling",
"forged an alliance with",
"decoded extraterrestrial messages, discovering",
"composed a song that captured",
"painted a portrait capturing",
"built a robot capable of",
"brewed a potion granting",
"navigated through a maze of challenges, relying on",
"composed a poem inspired by",
"embarked on a quest to rescue",
"discovered a hidden passage leading to",
"mastered the skill of",
"deciphered a code, unlocking",
"created an artwork reflecting",
"ventured into the realm of dreams, encountering",
"built a spaceship powered by",
"uncovered the truth about",
"composed a melody evoking",
"deciphered a prophecy foretelling"];

const ends = [
"the essence of life.",
"a world beyond imagination.",
"the mysteries of the universe.",
"an unforgettable adventure.",
"a love that transcends time.",
"the key to eternal happiness.",
"a new beginning.",
"the heart of the matter.",
"a tale for generations to come.",
"a legacy that would be remembered.",
"the secrets of the ancients.",
"a future filled with possibilities.",
"the answer to all questions.",
"the epitome of beauty.",
"a friendship that would last forever.",
"a truth that changed everything.",
"the magic within us all.",
"the power of human spirit.",
"a world full of wonders.",
"the triumph of good over evil.",
"the core of human existence.",
"the dawn of a new era.",
"a bond stronger than time itself.",
"the fabric of reality.",
"the essence of true happiness.",
"a melody that resonated in hearts.",
"the beauty of simplicity.",
"a vision of hope.",
"a masterpiece that touched souls.",
"the spirit of adventure.",
"the culmination of dreams.",
"the heartbeat of the universe.",
"a beacon of light in darkness.",
"the epitome of courage.",
"a revelation that shook the world.",
"the soul of creativity.",
"the essence of love and sacrifice.",
"the foundation of a new world.",
"the rhythm of life.",
"a spark of inspiration for all.",
"the embodiment of dreams.",
"a testament to human resilience.",
"the gateway to infinite possibilities.",
"the melody of the cosmos.",
"the core of human connection.",
"a journey worth taking.",
"the harmony of the universe.",
"the essence of true freedom.",
"the promise of a better tomorrow.",
"a story that would be told for ages."];


const nouns = [
"Dog",
"Cat",
"Bird",
"Fish",
"Elephant",
"Tiger",
"Butterfly",
"Snake",
"Lion",
"Monkey",
"Horse",
"Frog",
"Kangaroo",
"Giraffe",
"Dolphin",
"Penguin",
"Squirrel",
"Koala",
"Cheetah",
"Raccoon"];

const rng = (num) => {
  num = Math.floor(Math.random() * num);
  return num;
}


const message = `${beginnings[rng(beginnings.length)]}, the ${nouns[rng(nouns.length)]} ${middles[rng(middles.length)]} ${ends[rng(ends.length)]}`;

console.log(message);
